# _config.yml

# required, replace with your own information -----
title: Natalie Forsdick, PhD
author: Natalie Forsdick
description: > 
  Postdoctoral research fellow
baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
#---------------------------------------------------

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock

